---
# Test ansible

- name: test
  hosts: all
  sudo: true
  
  tasks:
    - name: install mc
      yum: name=mc state=present

    - name: stat key1
      stat: path=/vagrant/.vagrant/machines/node1/virtualbox/private_key
      register: key1_stat
      
    - name: copy key node 1
      copy: src=/vagrant/.vagrant/machines/node1/virtualbox/private_key dest=/home/vagrant/node1/ owner=vagrant group=vagrant mode=600
      when: (key1_stat.stat.exists and inventory_hostname in groups['controllers'])
      
    - name: stat key2
      stat: path=/vagrant/.vagrant/machines/node2/virtualbox/private_key
      register: key2_stat
    
    - name: copy key node 2
      copy: src=/vagrant/.vagrant/machines/node2/virtualbox/private_key dest=/home/vagrant/node2/ owner=vagrant group=vagrant mode=600
      when: (key2_stat.stat.exists and inventory_hostname in groups['controllers'])